# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(370, 40, 130, 130))
        self.picture.setObjectName("picture")
        self.wordLabel = QtWidgets.QLabel(self.centralwidget)
        self.wordLabel.setGeometry(QtCore.QRect(190, 230, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.wordLabel.setFont(font)
        self.wordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel.setWordWrap(True)
        self.wordLabel.setObjectName("wordLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 350, 781, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hintButton = QtWidgets.QPushButton(self.centralwidget)
        self.hintButton.setGeometry(QtCore.QRect(670, 30, 121, 91))
        self.hintButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture.setText(_translate("MainWindow", "PictureLabel"))
        self.wordLabel.setText(_translate("MainWindow", "_ _ _ _ _"))
        self.hintButton.setText(_translate("MainWindow", "Подсказка"))
