# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'levelchooser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelChooser(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("LevelChooser")
        Dialog.resize(411, 268)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 331, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.easyButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easyButton.sizePolicy().hasHeightForWidth())
        self.easyButton.setSizePolicy(sizePolicy)
        self.easyButton.setObjectName("easyButton")
        self.verticalLayout.addWidget(self.easyButton)
        self.normalButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalButton.sizePolicy().hasHeightForWidth())
        self.normalButton.setSizePolicy(sizePolicy)
        self.normalButton.setObjectName("normalButton")
        self.verticalLayout.addWidget(self.normalButton)
        self.hardButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardButton.sizePolicy().hasHeightForWidth())
        self.hardButton.setSizePolicy(sizePolicy)
        self.hardButton.setObjectName("hardButton")
        self.verticalLayout.addWidget(self.hardButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.easyButton.setText(_translate("Dialog", "Простые слова (50 опыта)"))
        self.normalButton.setText(_translate("Dialog", "Нормальные слова (100 опыта)"))
        self.hardButton.setText(_translate("Dialog", "Сложны слова (150 опыта)"))
