# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rules(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Rules")
        Dialog.resize(400, 300)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 361, 251))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Rules", "Rules"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto\',\'sans-serif\'; font-size:16pt; color:#333333; background-color:#ffffff;\">Виселица – </span><a href=\"https://minigames.mail.ru/info/igry/v_slova/\"><span style=\" font-family:\'Roboto\',\'sans-serif\'; font-size:16pt; font-weight:496; text-decoration: underline; color:#333333; background-color:#ffffff;\">игра в слова</span></a><span style=\" font-family:\'Roboto\',\'sans-serif\'; font-size:16pt; color:#333333; background-color:#ffffff;\">. Игроку загадывается слово, которое он должны угадать, используя буквы алфавита и возможность совершить ограниченное количество ошибок. </span></p></body></html>"))
